CREATE DATABASE IF NOT EXIST companydb;

USE companydb;

CREATE TABLE employee(
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
    salary INT(9) DEFAULT NULL,
    PRIMARY_KEY(id)
);
